#pragma once
#include <JuceHeader.h>

struct HelpManualPages
{
    static const int numPages = 5;
    static inline const char* pages[numPages] = {
        // Page 1
        "CHORDCRAFT STUDIO - OFFICIAL MANUAL\n"
        "PAGE 1: THE ARRANGER TIMELINE\n"
        "\n"
        "The Arranger is your main workspace. This\n"
        "is where you build your harmonic foundation.\n"
        "\n"
        "+-----------+\n"
        "|   C Maj   |  <-- Active Chord Block\n"
        "|    4/4    |\n"
        "+-----------+\n"
        "\n"
        "ACTIONS:\n"
        "\n"
        "ADD CHORDS: Tap empty space on grid to insert\n"
        "a new chord block.\n"
        "\n"
        "EDIT CHORDS: Tap block to open Inspector and\n"
        "change Root, Quality, or Duration.\n"
        "\n"
        "MULTI-SELECT: Press, hold, and drag across\n"
        "blocks to highlight multiple chords.\n"
        "\n"
        "BATCH ACTIONS: Use the blue \"COPY / PASTE\"\n"
        "drawers to duplicate sections or delete them.\n"
        "\n"
        "PREVIEW: Tap a block while transport is\n"
        "stopped to preview that chord.",
        
        // Page 2
        "CHORDCRAFT STUDIO - OFFICIAL MANUAL\n"
        "PAGE 2: HARMONIC ADVICE & THEORY\n"
        "\n"
        "Chordcraft actively evaluates your progression\n"
        "to suggest adjustments.\n"
        "\n"
        "COLOR-CODED TENSION:\n"
        "Block borders change color based on Key:\n"
        "[ GREEN ]  - Safe. Diatonic chord.\n"
        "[ YELLOW ] - Tension. Modal mixture/Secondary.\n"
        "[ RED ]    - Experimental. Highly chromatic.\n"
        "\n"
        "PASSING CHORDS:\n"
        "Select a block and tap \"Insert Passing Chord\".\n"
        "The engine calculates transitions (Secondary\n"
        "Dominants, Tritones) to the next chord.\n"
        "Tap options to audition transitions.",
        
        // Page 3
        "CHORDCRAFT STUDIO - OFFICIAL MANUAL\n"
        "PAGE 3: THE TRACK MIXER\n"
        "\n"
        "The Mixer manages instruments and patterns\n"
        "assigned to each track lane.\n"
        "\n"
        "ACTIONS:\n"
        "\n"
        "Tap \"MIXER\" button at the bottom of\n"
        "the screen to open the track list.\n"
        "\n"
        "TRACK LANES: Dynamic track count with independent\n"
        "volume sliders.\n"
        "\n"
        "INSTRUMENTS: Select General MIDI presets\n"
        "(Piano, Guitar, Strings, Bass, Synth).\n"
        "\n"
        "PATTERNS: Assign genre-specific rhythmic\n"
        "grooves or arpeggios per lane.\n"
        "\n"
        "PRO TIP: Add a \"Hold\" pattern to Strings, a\n"
        "\"Hammered\" pattern to Piano, and a \"Bassline\"\n"
        "pattern to Synth Bass for a full arrangement.",
        
        // Page 4
        "CHORDCRAFT STUDIO - OFFICIAL MANUAL\n"
        "PAGE 4: GLOBAL MENU & AUTO-COMPOSER\n"
        "\n"
        "Tap the purple \"MENU\" button to access\n"
        "project-level controls.\n"
        "\n"
        "ACTIONS:\n"
        "\n"
        "SAVE / OPEN: Store arrangement to device or\n"
        "load previous sketches.\n"
        "\n"
        "KEY TRANSPOSE: Shift the project key.\n"
        "All blocks transpose mathematically while\n"
        "preserving relative intervals.\n"
        "\n"
        "AUTO-COMPOSER: Generate genre-specific\n"
        "chord progression sketches instantly.\n"
        "\n"
        "TEMPO: Drag or click BPM button in Inspector\n"
        "to adjust tempo globally or per-section.",
        
        // Page 5
        "CHORDCRAFT STUDIO - OFFICIAL MANUAL\n"
        "PAGE 5: EXPORT & STUDIO ROUTING\n"
        "\n"
        "Chordcraft connects directly with desktop DAWs\n"
        "and external synthesizers.\n"
        "\n"
        "ACTIONS:\n"
        "\n"
        "MIDI EXPORT: Generates Type-1 Multitrack MIDI.\n"
        "Retains track and tempo separations.\n"
        "\n"
        "AUDIO BOUNCE: Renders arrangement instantly\n"
        "to a 24-bit stereo WAV file.\n"
        "\n"
        "SHEET MUSIC: Generates PDF vector sheet music\n"
        "with clean staves and key signatures.\n"
        "\n"
        "LIVE MIDI OUT:\n"
        "Connect via USB. Chordcraft outputs MIDI\n"
        "on channels 1-16 for external synths."
    };
};
